
imports:
    - { resource: base.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing/development.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

#doctrine:
#    dbal:
#        dbname: %app.database.name%_development
